Add validations to `ssh-key add`

diff --git a/bin/git-ssh-key b/bin/git-ssh-key
--- a/bin/git-ssh-key
+++ b/bin/git-ssh-key
@@ -1,7 +1,9 @@
 #!/bin/sh
 
 _git_ssh_key_usage(){
-  echo "$0"
+  echo "git ssh-key
+git ssh-key add <title> <key_file>
+git ssh-key rm <key_id>"
 }
 
 _git_ssh_key_list(){
@@ -12,6 +14,11 @@ _git_ssh_key_list(){
 _git_ssh_key_add(){
   title="$1"
   pubkey_file="$2"
+
+  test -z "$title" && echo "title required" 1>&2 && exit 1
+  test -z "$pubkey_file" && echo "key file required" 1>&2 && exit 2
+  test ! -e "$pubkey_file" && echo "No such key file '$pubkey_file'" 1>&2 && exit 3
+
   body="{\"title\": \"$title\", \"key\": \"$(cat $pubkey_file)\"}"
   git api POST /user/keys "$body" > /dev/null && echo "ssh-key was created"
 }
